export const CONFIG = {
  cantidadEstrellas: 160,
  texturaRosa: './assets/rosa.png',

  sol: {
    nombre: 'El Sol',
    info: 'Lasso - No Pares de Bailar',
    radio: 2,
    textura: './assets/sol.jpg',
    video: './assets/lasso-no-pares-de-bailar.mp4',
    colorFallback: 0xffaa00,
    colorTema: '#ffaa00',
    mensajeReverso: 'El sol se enamoró de la luna, y la luna del sol aunque sabían que no podían estar juntos, pero a veces se juntan y les importa un carajo si el mundo se oscurece!!.',
    letras: [
      { time: 12, text: 'El sol juega con tu pelo' },
      { time: 17, text: 'Bailas y paras el tiempo, todos te están viendo' },
      { time: 23, text: 'Nada normal, es original, en trance estoy' },
      { time: 29, text: 'Y así defines arte sin siquiera despeinarte' },
      { time: 37, text: 'Lo lamento, no sé escribir' },
      { time: 41, text: 'Ojalá pudiera describir' },
      { time: 46, text: 'En pocas palabras, lo que eres para mí' },
      { time: 55, text: 'En pocas palabras, lo que eres para mí' },
      { time: 70, text: 'Veo cómo la luz' },
      { time: 75, text: 'Salta de tu cara al suelo y regresa' },
      { time: 81, text: 'Hay veces que te pierdo en el mar de gente' },
      { time: 87, text: 'Pero, es fácil encontrarte porque eres diferente' },
      { time: 97, text: 'Lo lamento, no sé escribir' },
      { time: 101, text: 'Ojalá pudiera describir' },
      { time: 104, text: 'En pocas palabras, lo que eres para mí' },
      { time: 109, text: 'En pocas palabras, lo que eres para mí' },
      { time: 116, text: 'Yo no busco una razón para llamar tu atención' },
      { time: 120, text: 'Solo quiero que no pares de bailar' },
      { time: 129, text: 'Yo no busco una razón para entrar en tu corazón' },
      { time: 136, text: 'Solo quiero que no pares de bailar' },
      { time: 144, text: 'No pares de bailar' },
      { time: 149, text: 'En pocas palabras, eres todo para mí' },
      { time: 154, text: 'En pocas palabras, eres todo para mí' },
      { time: 161, text: 'En pocas palabras, eres todo para, todo para mí' },
      { time: 166, text: 'Mí, mí' }
    ]
  },

  planetas: [
    {
      nombre: 'Mercurio',
      textura: './assets/mercurio.jpg',
      radio: 0.3,
      distancia: 4,
      velocidad: 0.8,
      colorFallback: 0x9e9e9e,
      colorTema: '#a0a0a0',
      info: 'Alex Ubago & Amaia Montero - Sin Miedo A Nada.',
      video: './assets/alex-ubago-sin-miedo-a-nada.mp4',
      mensajeReverso: 'El universo necesitó miles de millones de años para llegar hasta este instante. Yo solo necesitaba conocerte para querer detener el tiempo.',
      letras: [
        { time: 5, text: 'Me muero por suplicarte que no te vayas' },
        { time: 10, text: 'Mi vida, me muero por escucharte' },
        { time: 16, text: 'Decir las cosas que nunca digas' },
        { time: 21, text: 'Mas me callo y te marchas' },
        { time: 25, text: 'Aún tengo la esperanza' },
        { time: 27, text: 'De ser capaz algún día' },
        { time: 30, text: 'De no esconder las heridas que me duelen' },
        { time: 35, text: 'Al pensar que te voy queriendo cada día' },
        { time: 43, text: '¿Cuánto tiempo vamos a esperar?' },
        { time: 52, text: 'Me muero por abrazarte' },
        { time: 56, text: 'Y que me abraces tan fuerte' },
        { time: 59, text: 'Me muero por divertirte' },
        { time: 64, text: 'Y que me beses cuando despierte' },
        { time: 67, text: 'Acomodado en tu pecho' },
        { time: 71, text: 'Hasta que el sol aparezca' },
        { time: 74, text: 'Me voy perdiendo en tu aroma' },
        { time: 78, text: 'Me voy perdiendo en tus labios que se acercan' },
        { time: 81, text: 'Susurrando palabras que llegan a este pobre corazón' },
        { time: 90, text: 'Voy sintiendo el fuego en mi interior' },
        { time: 95, text: 'Me muero por conocerte' },
        { time: 98, text: 'Saber qué es lo que piensas' },
        { time: 104, text: 'Abrir todas tus puertas' },
        { time: 109, text: 'Y vencer esas tormentas que nos quieran abatir' },
        { time: 113, text: 'Centrar en tus ojos mi mirada' },
        { time: 117, text: 'Cantar contigo al alba' },
        { time: 120, text: 'Besarnos hasta desgastar nuestros labios' },
        { time: 127, text: 'Y ver en tu rostro cada día' },
        { time: 131, text: 'Crecer esa semilla' },
        { time: 135, text: 'Crear, soñar, dejar todo surgir' },
        { time: 141, text: 'Apartando el miedo a sufrir' },
        { time: 150, text: 'Me muero por explicarte lo que pasa por mi mente' },
        { time: 157, text: 'Me muero por intrigarte y seguir siendo capaz de sorprenderte' },
        { time: 165, text: 'Sentir cada día ese flechazo al verte' },
        { time: 171, text: '¿Qué más dará lo que digan?' },
        { time: 175, text: '¿Qué más dará lo que piensen?' },
        { time: 178, text: 'Si estoy loca es cosa mía' },
        { time: 181, text: 'Y ahora vuelvo a mirar, el mundo a mi favor' },
        { time: 188, text: 'Vuelvo a ver brillar la luz del sol' }
      ]
    },
    {
      nombre: 'Venus',
      textura: './assets/venus.jpg',
      radio: 0.5,
      distancia: 6,
      velocidad: 0.6,
      colorFallback: 0xe3bb76,
      colorTema: '#e8b86d',
      info: 'Sin Bandera - Te Vi Venir',
      video: './assets/Sin-Bandera-Te-Vi-Venir.mp4',
      mensajeReverso: 'Te quiero ver y no puedo. Te quiero tener y no te tengo. Lo único que puedo hacer es quererte en silencio. Y no importa a qué hora mires esto, solo quiero decirte que hoy estoy pensando en ti como siempre.',
      letras: [
        { time: 14, text: 'Aún ni siquiera te tengo' },
        { time: 18, text: 'y ya tengo miedo de perderte, amor' },
        { time: 20, text: 'qué rápido se me ha clavado' },
        { time: 23, text: 'que dentro todo este dolor' },
        { time: 27, text: 'es poco lo que te conozco' },
        { time: 31, text: 'y ya pongo todo el juego a tu favor' },
        { time: 34, text: 'no tengo miedo de apostarte' },
        { time: 37, text: 'perderte sí me da pavor' },
        { time: 41, text: 'no me queda más refugio que la fantasía' },
        { time: 48, text: 'no me queda más que hacer' },
        { time: 52, text: 'que hacerte una poesía' },
        { time: 55, text: 'porque te vi venir y no dudé' },
        { time: 59, text: 'te vi llegar y te abracé' },
        { time: 64, text: 'y puse toda mi pasión para que te quedaras' },
        { time: 72, text: 'y luego te besé y me arriesgué con la verdad' },
        { time: 78, text: 'te acaricié y al fin abrí mi corazón para que tú pasaras' },
        { time: 85, text: 'mi amor te di sin condición para que te quedaras' },
        { time: 92, text: 'ahora esperar algunos días' },
        { time: 95, text: 'para ver si lo que te di fue suficiente' },
        { time: 98, text: 'no sabes qué terror se siente' },
        { time: 102, text: 'la espera cada madrugada' },
        { time: 107, text: 'si tú ya no quisieras volver' },
        { time: 110, text: 'se perdería el sentido del amor por siempre' },
        { time: 114, text: 'no entendería ya este mundo' },
        { time: 117, text: 'me alejaría de la gente' },
        { time: 120, text: 'no me queda más refugio, que la fantasía' },
        { time: 129, text: 'no me queda más que hacer' },
        { time: 132, text: 'que hacerte una poesía' },
        { time: 135, text: 'porque te vi venir y no dudé' },
        { time: 138, text: 'te vi llegar y te abracé' },
        { time: 142, text: 'y puse toda mi pasión para que te quedaras' },
        { time: 150, text: 'y luego te besé y me arriesgué con la verdad' },
        { time: 156, text: 'te acaricié y al fin abrí mi corazón para que tú pasaras' },
        { time: 163, text: 'mi amor te di sin condición para que te quedaras' },
        { time: 169, text: 'mi amor te di sin condición para que te quedaras' },
        { time: 175, text: 'mi amor te di sin condición para que te quedaras' }
      ]
    },
    {
      nombre: 'Tierra',
      textura: './assets/tierra.jpg',
      radio: 0.55,
      distancia: 8.5,
      velocidad: 0.4,
      colorFallback: 0x2b82c9,
      colorTema: '#2e93d8',
      info: 'Andrés Cepeda - Un Ratito',
      video: './assets/Andrés-Cepeda-Un-Ratito.mp4',
      mensajeReverso: 'Entre miles de rosas, tú no serías la más linda, sino la más hermosa, porque entre todas ellas ninguna tendría tu dulce aroma.',
      letras: [
        { time: 14, text: 'Aléjate un poquito a ver qué pasa cuando' },
        { time: 18, text: 'Estás a más de tres pasitos de mi piel' },
        { time: 24, text: 'Probemos tu fe por leche yo por pan pero' },
        { time: 28, text: 'Encontremos en la mitad' },
        { time: 32, text: 'No creo resistir tanto la distancia' },
        { time: 37, text: 'Suéltame de tu mano' },
        { time: 42, text: 'Si puedo seguir de pie no habrá sido en vano' },
        { time: 50, text: 'Enséñame a estar sin ti' },
        { time: 54, text: 'Un minuto una hora un día' },
        { time: 60, text: 'Quiero aprender cómo es vivir' },
        { time: 66, text: 'Un ratito sin tu compañía' },
        { time: 72, text: 'Me acostumbré a hacer tu sombra fiel' },
        { time: 77, text: 'Y ahora es tan difícil recordar quién soy' },
        { time: 84, text: 'Demuéstrame que sale el sol' },
        { time: 90, text: 'El segundo en el que no me miras ya soy' },
        { time: 96, text: 'Entrénate, desaparece de mi vista' },
        { time: 102, text: 'Que necesito practicar' },
        { time: 106, text: 'Ay niña quién sabe si soportaré' },
        { time: 110, text: 'Tener tu foto en la pared colgada' },
        { time: 115, text: 'Y privarme de tu cara bonita' },
        { time: 119, text: 'Suéltame de tu mano' },
        { time: 122, text: 'Si puedo seguir de pie no habrá sido en vano' },
        { time: 129, text: 'Enséñame a estar sin ti' },
        { time: 134, text: 'Un minuto una hora un día' },
        { time: 141, text: 'Quiero aprender cómo es vivir' },
        { time: 145, text: 'Un ratito sin tu compañía' },
        { time: 152, text: 'Me acostumbré a hacer tu sombra fiel' },
        { time: 156, text: 'Y ahora es tan difícil recordar quién soy' },
        { time: 163, text: 'Demuéstrame que sale el sol' },
        { time: 168, text: 'El segundo en el que no me miras' },
        { time: 173, text: 'Un ratito sin tu compañía' },
        { time: 180, text: 'Un ratito sin tu compañía' },
        { time: 184, text: 'Oh oh, si puedo seguir de pie no habrá sido en vano' },
        { time: 197, text: 'Enséñame a estar sin ti' },
        { time: 201, text: 'Un minuto una hora un día' },
        { time: 209, text: 'Demuéstrame que salga el sol' },
        { time: 213, text: 'El segundo en el que no me mira' }
      ]
    },
    {
      nombre: 'Marte',
      textura: './assets/marte.jpg',
      radio: 0.4,
      distancia: 11,
      velocidad: 0.3,
      colorFallback: 0xc1440e,
      colorTema: '#e05324',
      info: 'Chayanne - Dejaría Todo',
      video: './assets/Chayanne-Dejaría-Todo.mp4',
      mensajeReverso: 'Por si nadie te lo ha dicho, a mí sí me importan tus problemas, a mí sí me importa tu salud, a mí sí me importan tus mensajes, a mí sí me importa cómo fue tu día, a mí sí me importa verte, a mí sí me importa escuchar tu opinión. En fin, a mí sí me importas, y muchísimo.',
      letras: [
      { time: 28, text: 'He intentado casi todo para convencerte' },
      { time: 35, text: 'Mientras el mundo se derrumba, todo aquí a mis pies' },
      { time: 41, text: 'Mientras aprendo de esta soledad que desconozco' },
      { time: 48, text: 'Me vuelvo a preguntar, quizás sí sobreviviré' },
      { time: 54, text: 'Porque sin ti, me queda la conciencia helada y vacía' },
      { time: 61, text: 'Porque sin ti, me he dado cuenta, amor, que no renaceré' },
      { time: 67, text: 'Porque yo he ido más allá del límite de la desolación' },
      { time: 74, text: 'Mi cuerpo, mi mente y mi alma ya no tienen conexión' },
      { time: 80, text: 'Y yo te juro que' },
      { time: 83, text: 'Lo dejaría todo porque te quedaras' },
      { time: 87, text: 'Mi credo, mi pasado, mi religión' },
      { time: 91, text: 'Después de todo, estás rompiendo nuestros lazos' },
      { time: 94, text: 'Y dejas en pedazos a este corazón' },
      { time: 97, text: 'Mi piel, también la dejaría' },
      { time: 100, text: 'Mi nombre, mi fuerza, hasta mi propia vida' },
      { time: 105, text: '¿Y qué más da perder? Si te llevas del todo mi fe' },
      { time: 135, text: 'Duelen más tus cosas buenas cuando estás ausente' },
      { time: 141, text: 'Yo sé que es demasiado tarde para remediar' },
      { time: 148, text: 'No me queda bien valerme de diez mil excusas' },
      { time: 154, text: 'Cuando definitivamente, sé que ahora te vas' },
      { time: 161, text: 'Aunque te vuelvo a repetir que estoy muriendo día a día' },
      { time: 167, text: 'Aunque también estés muriendo, tú no me perdonarás' },
      { time: 174, text: 'Aunque sin ti haya llegado al límite de la desolación' },
      { time: 181, text: 'Mi cuerpo, mi mente y mi alma ya no tienen conexión' },
      { time: 186, text: 'Sigo muriéndome' },
      { time: 191, text: 'Lo dejaría todo porque te quedaras...' }
      ]
    },
    {
      nombre: 'Júpiter',
      textura: './assets/jupiter.jpg',
      radio: 1.5,
      distancia: 16,
      velocidad: 0.15,
      colorFallback: 0xd39c7e,
      colorTema: '#d89668',
      info: 'Melendi - Destino o Casualidad ft. Ha*Ash',
      video: './assets/Melendi-Destino-o-Casualidad.mp4',
      mensajeReverso: 'Me dijieron que para enamorarte tenia que hacerte sonreír, pero cuando te veo sonreír el que se enamora soy yo.',
      letras: [
        { time: 28, text: 'He intentado casi todo para convencerte' },
        { time: 35, text: 'Mientras el mundo se derrumba, todo aquí a mis pies' },
        { time: 41, text: 'Mientras aprendo de esta soledad que desconozco' },
        { time: 48, text: 'Me vuelvo a preguntar, quizás sí sobreviviré' },
        { time: 54, text: 'Porque sin ti, me queda la conciencia helada y vacía' },
        { time: 61, text: 'Porque sin ti, me he dado cuenta, amor, que no renaceré' },
        { time: 67, text: 'Porque yo he ido más allá del límite de la desolación' },
        { time: 74, text: 'Mi cuerpo, mi mente y mi alma ya no tienen conexión' },
        { time: 80, text: 'Y yo te juro que' },
        { time: 83, text: 'Lo dejaría todo porque te quedaras' },
        { time: 87, text: 'Mi credo, mi pasado, mi religión' },
        { time: 91, text: 'Después de todo, estás rompiendo nuestros lazos' },
        { time: 94, text: 'Y dejas en pedazos a este corazón' },
        { time: 97, text: 'Mi piel, también la dejaría' },
        { time: 100, text: 'Mi nombre, mi fuerza, hasta mi propia vida' },
        { time: 105, text: '¿Y qué más da perder?' },
        { time: 109, text: 'Si te llevas del todo mi fe' },
        { time: 112, text: '¡Qué no dejaría!' },
        { time: 135, text: 'Duelen más tus cosas buenas cuando estás ausente' },
        { time: 141, text: 'Yo sé que es demasiado tarde para remediar' },
        { time: 148, text: 'No me queda bien valerme de diez mil excusas' },
        { time: 154, text: 'Cuando definitivamente, sé que ahora te vas' },
        { time: 161, text: 'Aunque te vuelvo a repetir que estoy muriendo día a día' },
        { time: 167, text: 'Aunque también estés muriendo, tú no me perdonarás' },
        { time: 174, text: 'Aunque sin ti haya llegado al límite de la desolación' },
        { time: 181, text: 'Mi cuerpo, mi mente y mi alma ya no tienen conexión' },
        { time: 186, text: 'Sigo muriéndome' },
        { time: 191, text: 'Lo dejaría todo porque te quedaras' }
      ]
    },
    {
      nombre: 'Saturno',
      textura: './assets/saturno.jpg',
      radio: 1.2,
      distancia: 21,
      velocidad: 0.1,
      colorFallback: 0xc5ab6e,
      colorTema: '#e2c575',
      video: './assets/pablo-alborán-por-fin.mp4',
      tieneAnillo: true,
      info: 'Pablo Alborán - Por fin.',
      mensajeReverso: 'Incluso si nuestros gustos no coinciden, me gustaria ver tus series favoritas, probar la comida que te encanta, ir a esos lugares que te hacen feliz, escuchar tu artista favorito y descubrir todo lo que te gusta, solo para entenderte un poquito más.',
      letras: [
        { time: 14, text: 'Qué intenso es esto del amor, qué garra tiene el corazón' },
        { time: 21, text: 'Jamás pensé que sucediera así' },
        { time: 26, text: 'Bendita toda conexión entre tu alma y mi voz' },
        { time: 34, text: 'Y jamás creí que me iba a suceder a mí' },
        { time: 40, text: 'Por fin lo puedo sentir, te conozco y te reconozco' },
        { time: 53, text: 'Que por fin sé lo que es vivir con un suspiro en el pecho' },
        { time: 62, text: 'Con cosquillas por dentro' },
        { time: 66, text: 'Y por fin sé por qué estoy así' },
        { time: 75, text: 'Tú me has hecho mejor, mejor de lo que era' },
        { time: 81, text: 'Y entregaría mi voz a cambio de una vida entera' },
        { time: 88, text: 'Tú me has hecho entender que aquí nada es eterno' },
        { time: 94, text: 'Pero tu piel y mi piel pueden detener el tiempo' },
        { time: 117, text: 'Parado de pensar hasta donde soy capaz de llegar' },
        { time: 123, text: 'Ya que mi vida está en tus manos y en tu boca' },
        { time: 126, text: 'Me he convertido en lo que nunca imaginé' },
        { time: 130, text: 'Has dividido en dos mi alma y mi ser' },
        { time: 133, text: 'Porque una parte va contigo aunque a veces no lo sepas ver' },
        { time: 140, text: 'Por fin lo puedo sentir, te conozco y te reconozco' },
        { time: 153, text: 'Que por fin sé lo que es vivir con un suspiro en el pecho' },
        { time: 163, text: 'Y con cosquillas por dentro' },
        { time: 166, text: 'Por fin sé por qué estoy así' },
        { time: 172, text: 'Tú me has hecho mejor, mejor de lo que era' },
        { time: 178, text: 'Y entregaría mi voz a cambio de una vida entera' },
        { time: 185, text: 'Tú me has hecho entender que aquí nada es eterno' },
        { time: 191, text: 'Pero tu piel y mi piel pueden detener el tiempo' }
      ]
    },
    {
      nombre: 'Urano',
      textura: './assets/urano.jpg',
      radio: 0.8,
      distancia: 26,
      velocidad: 0.07,
      colorFallback: 0x4dd0e1,
      colorTema: '#4dd0e1',
      video: './assets/Ed-Sheeran-Perfect.mp4',
      info: 'Ed Sheeran - Perfect.',
      mensajeReverso: 'Perdón por insistir tanto, pero me arrepentiría el resto de mi vida si no hago hasta lo imposible para que te quedes.',
      letras: [
        { time: 21, text: 'I found a' },
        { time: 23, text: 'love for me.' },
        { time: 28, text: 'Darling, just dive right' },
        { time: 31, text: 'in. Follow my' },
        { time: 35, text: 'lead. Well, I found a' },
        { time: 39, text: 'girl. Beautiful and' },
        { time: 42, text: 'sweet. Well, I never knew you were the' },
        { time: 46, text: 'someone waiting for' },
        { time: 49, text: 'me. \'Cuz we were just kids when we fell' },
        { time: 53, text: 'in love. Not knowing what if. Boys, I' },
        { time: 59, text: 'will not give you up this' },
        { time: 65, text: 'time. Darling, just kiss me slow. Your' },
        { time: 70, text: 'heart is all I own. And in your eyes,' },
        { time: 76, text: 'your hope and' },
        { time: 80, text: 'mine,' },
        { time: 81, text: 'baby,' },
        { time: 83, text: 'I\'m dancing in the dark.' },
        { time: 88, text: 'With you between my' },
        { time: 91, text: 'arms, barefoot on the' },
        { time: 95, text: 'cross, listening to our favorite song.' },
        { time: 99, text: 'When you said you looked a mess, I' },
        { time: 103, text: 'whispered underneath my breath, but you' },
        { time: 107, text: 'heard it. Darling, you look perfect' },
        { time: 112, text: 'tonight.' },
        { time: 119, text: 'Well, I found a' },
        { time: 122, text: 'woman stronger than anyone I' },
        { time: 126, text: 'know. She shares my dreams. I hope that' },
        { time: 130, text: 'someday I\'ll share her' },
        { time: 133, text: 'home. I found the' },
        { time: 138, text: 'love to carry more than just my secrets.' },
        { time: 143, text: 'To carry love. to carry children of our' },
        { time: 148, text: 'own. We are still kids, but we\'re so in' },
        { time: 153, text: 'love fighting against' },
        { time: 156, text: 'stars. I know we\'ll be all' },
        { time: 161, text: 'right' },
        { time: 164, text: 'time, darling. Hold my' },
        { time: 169, text: 'hand' },
        { time: 171, text: 'be. I see the' },
        { time: 174, text: 'future in' },
        { time: 178, text: 'light.' },
        { time: 180, text: 'Maybe' },
        { time: 182, text: 'I dancing in the' },
        { time: 185, text: 'dark with you between my' },
        { time: 191, text: 'arms on the' },
        { time: 193, text: 'cross. Listening to our favorite song.' },
        { time: 197, text: 'When I saw you in that dress looking so' },
        { time: 202, text: 'beautiful. I' },
        { time: 206, text: 'don\'t call' },
        { time: 209, text: 'you' },
        { time: 224, text: 'perfect baby.' },
        { time: 228, text: 'Dancing in the' },
        { time: 231, text: 'dark. You between my' },
        { time: 236, text: 'arms of the' },
        { time: 239, text: 'cross. Listening to our favorite song. I' },
        { time: 243, text: 'have faith in what I see. I know I have' },
        { time: 248, text: 'met an' },
        { time: 250, text: 'angel in person.' },
        { time: 253, text: 'She looks perfect. I don\'t' },
        { time: 259, text: 'deserve this. You look perfect tonight.' }
      ]
    },
    {
      nombre: 'Neptuno',
      textura: './assets/neptuno.jpg',
      radio: 0.75,
      distancia: 31,
      velocidad: 0.05,
      colorFallback: 0x3d5afe,
      colorTema: '#4464f2',
      tieneAnilloGravedad: true,
      tieneBailarines: true,
      info: 'New West - Those Eyes.',
      video: './assets/New-West-Those-Eyes.mp4',
      mensajeReverso: 'No siempre tengo cosas interesantes que contarte pero siempre tengo ganas de hablar contigo.',
      letras: [
        { time: 0, text: 'When we\'re out in a crowd, laughing loud' },
        { time: 5, text: 'And nobody knows why' },
        { time: 11, text: 'When we\'re lost at a club, gettin\' drunk' },
        { time: 16, text: 'And you give me that smile' },
        { time: 23, text: 'Going home in the back of a car' },
        { time: 29, text: 'And your hand touches mine' },
        { time: 35, text: 'When we\'re done making love' },
        { time: 40, text: 'And you look up and give me those eyes' },
        { time: 47, text: '\'Cause all of the small things that you do' },
        { time: 53, text: 'Are what remind me why I fell for you' },
        { time: 60, text: 'And when we\'re apart and I\'m missing you' },
        { time: 65, text: 'I close my eyes and all I see is you' },
        { time: 71, text: 'And the small things you do' },
        { time: 87, text: 'When you call me at night while you\'re out' },
        { time: 92, text: 'Getting high with your friends' },
        { time: 95, text: 'Every high, every lie, every I love you' },
        { time: 104, text: 'You\'ve ever said' },
        { time: 107, text: '\'Cause all of the small things that you do' },
        { time: 113, text: 'Are what remind me why I fell for you' },
        { time: 120, text: 'And when we\'re apart and I\'m missing you' },
        { time: 125, text: 'I close my eyes and all I see is you' },
        { time: 131, text: 'And the small things you do' },
        { time: 156, text: 'When we\'re done making love' },
        { time: 161, text: 'And you look up and give me those eyes' },
        { time: 167, text: '\'Cause all of the small things that you do' },
        { time: 173, text: 'Are what remind me why I fell for you' },
        { time: 178, text: 'And when we\'re apart and I\'m missing you' },
        { time: 185, text: 'I close my eyes and all I see is you' },
        { time: 191, text: 'And the small things you do' }
      ]
    }
  ],

  palabrasBonitas: [
    'Eres mi paz', 'Eres mi hogar', 'Eres mi alegría', 'Eres mi felicidad',
    'Eres mi mundo', 'Eres mi inspiración', 'Eres mi sueño', 'Eres mi razón',
    'Eres mi persona favorita', 'Eres mi lugar favorito', 'Eres muy especial',
    'Eres única', 'Eres increíble', 'Eres maravillosa', 'Eres hermosa',
    'Eres perfecta para mí', 'Me encantas', 'Me haces feliz', 'Me haces sonreír',
    'Me encanta tu sonrisa', 'Me encanta tu mirada', 'Me encanta tu forma de ser',
    'Me encanta estar contigo', 'Me encanta tenerte', 'Me encanta pensarte',
    'Me encanta escucharte', 'Me encanta conocerte', 'Me encanta coincidir contigo',
    'Me haces sentir especial', 'Me haces sentir en casa', 'Pienso mucho en ti',
    'Siempre pienso en ti', 'Siempre estás en mi corazón', 'Siempre estás en mi mente',
    'Siempre tú', 'Solo tú', 'Quiero estar contigo', 'Quiero verte sonreír',
    'Quiero cuidarte', 'Quiero acompañarte', 'Quiero hacerte feliz',
    'Quiero compartir contigo', 'Quiero seguir contigo', 'Te quiero mucho',
    'Te quiero cada día más', 'Te adoro', 'Te extraño', 'Te pienso',
    'Te admiro', 'Te elijo', 'Te cuido', 'Te acompaño', 'Te llevo conmigo',
    'Te llevo en mi corazón', 'Te llevo en mis pensamientos', 'Gracias por existir',
    'Gracias por llegar', 'Gracias por estar', 'Gracias por ser tú',
    'Gracias por hacerme feliz', 'Qué bonito tenerte', 'Qué bonito conocerte',
    'Qué bonito coincidir', 'Qué bonito encontrarte', 'Qué bonito quererte',
    'Qué bonito compartir contigo', 'Contigo todo es bonito', 'Contigo todo tiene sentido',
    'Contigo estoy feliz', 'Contigo me siento bien', 'Contigo soy feliz',
    'Contigo quiero estar', 'Contigo me siento en casa', 'Contigo aprendí a sonreír',
    'Tu sonrisa me encanta', 'Tu mirada me enamora', 'Tu forma de ser me encanta',
    'Tu presencia me alegra', 'Tu voz me encanta', 'Tu cariño me hace feliz',
    'Tu amor es especial', 'Tu sonrisa ilumina todo', 'Eres mi casualidad favorita',
    'Eres mi coincidencia favorita', 'Eres mi pensamiento favorito',
    'Eres mi sonrisa favorita', 'Eres mi bonito destino', 'Eres una parte de mí',
    'Eres parte de mis días', 'Eres parte de mis sueños', 'Eres lo bonito de mis días',
    'Eres esa persona especial', 'Eres alguien increíble', 'Eres un regalo de la vida',
    'Me alegra haberte encontrado', 'Me alegra tenerte en mi vida',
    'Me alegra coincidir contigo', 'Me haces querer quedarme',
    'Siempre elegiría conocerte', 'TE AMO'
  ],

  canciones: [
    {
      titulo: 'Love Story',
      artista: 'Indila',
      ruta: './assets/Indila - Love Story.mp3'
    },
    {
      titulo: 'Chainsaw Man',
      artista: 'Kensuke Ushio',
      ruta: './assets/Chainsaw Man Reze Arc OST - in the pool.mp3'
    },
    {
      titulo: 'Luna',
      artista: 'Zoe',
      ruta: './assets/Zoe-LunaPiano.mp3'
    },
    {
      titulo: 'Desde mi Cielo',
      artista: 'Mago de Oz',
      ruta: './assets/DesdemiCielo-MagodeOz.mp3'
    },
    {
      titulo: 'Ofelia',
      artista: 'Juan Arenosa',
      ruta: './assets/JuanArenosa-Ofelia.mp3'
    },
    {
      titulo: 'Synthesia',
      artista: 'marvin palacios',
      ruta: './assets/piano2.mp3'
    }
  ]
};