export const CONFIG = {
  cantidadEstrellas: 160, // Cantidad de rosas flotantes
  texturaRosa: "./assets/rosa.png", // Imagen personalizada local
  sol: {
    nombre: "El Sol",
    info: "Lasso - No Pares de Bailar",
    radio: 2,
    textura: "https://raw.githubusercontent.com/mrdoob/three.js/r128/examples/textures/planets/moon_1024.jpg",
    video: "./assets/lasso-no-pares-de-bailar.mp4",
    colorFallback: 0xffaa00,
    colorTema: "#ffaa00",
    mensajeReverso: "Eres la luz y la energía que hace brillar todo mi universo."
  },
  planetas: [
    {
      nombre: "Mercurio",
      textura: "https://raw.githubusercontent.com/mrdoob/three.js/r128/examples/textures/planets/moon_1024.jpg",
      radio: 0.3,
      distancia: 4,
      velocidad: 0.8,
      colorFallback: 0x9e9e9e,
      colorTema: "#a0a0a0",
      info: "Alex Ubago & Amaia Montero - Sin Miedo A Nada.",
      video: "./assets/alex-ubago-sin-miedo-a-nada.mp4",
      mensajeReverso: "Pequeño pero resistente ante cualquier calor e intensidad."
    },
    {
      nombre: "Venus",
      textura: "https://raw.githubusercontent.com/mrdoob/three.js/r128/examples/textures/planets/moon_1024.jpg",
      radio: 0.5,
      distancia: 6,
      velocidad: 0.6,
      colorFallback: 0xe3bb76,
      colorTema: "#e8b86d",
      info: "Sin Bandera - Te Vi Venir",
      video: "./assets/Sin-Bandera-Te-Vi-Venir.mp4",
      mensajeReverso: "Un mundo que resplandece como el lucero más hermoso del cielo."
    },
    {
      nombre: "Tierra",
      textura: "https://raw.githubusercontent.com/mrdoob/three.js/r128/examples/textures/planets/earth_atmos_2048.jpg",
      radio: 0.55,
      distancia: 8.5,
      velocidad: 0.4,
      colorFallback: 0x2b82c9,
      colorTema: "#2e93d8",
      info: "Andrés Cepeda - Un Ratito",
      video: "./assets/Andrés-Cepeda-Un-Ratito.mp4",
      mensajeReverso: "No pares de bailar. Que este universo siempre tenga una canción para nosotros."
    },
    {
      nombre: "Marte",
      textura: "https://raw.githubusercontent.com/mrdoob/three.js/r128/examples/textures/planets/moon_1024.jpg",
      radio: 0.4,
      distancia: 11,
      velocidad: 0.3,
      colorFallback: 0xc1440e,
      colorTema: "#e05324",
      info: "Chayanne - Dejaría Todo",
      video: "./assets/Chayanne-Dejaría-Todo.mp4",
      mensajeReverso: "La pasión, el coraje y la fuerza viva en cada rincón."
    },
    {
      nombre: "Júpiter",
      textura: "https://raw.githubusercontent.com/mrdoob/three.js/r128/examples/textures/planets/moon_1024.jpg",
      radio: 1.5,
      distancia: 16,
      velocidad: 0.15,
      colorFallback: 0xd39c7e,
      colorTema: "#d89668",
      info: "Melendi - Destino o Casualidad ft. Ha*Ash",
      video: "./assets/Melendi-Destino-o-Casualidad.mp4",
      mensajeReverso: "Un corazón inmenso y protector capaz de albergar mundos."
    },
    {
      nombre: "Saturno",
      textura: "https://raw.githubusercontent.com/mrdoob/three.js/r128/examples/textures/planets/moon_1024.jpg",
      radio: 1.2,
      distancia: 21,
      velocidad: 0.1,
      colorFallback: 0xc5ab6e,
      colorTema: "#e2c575",
      video: "./assets/pablo-alborán-por-fin.mp4",
      tieneAnillo: true,
      info: "Pablo Alborán - Por fin.",
      mensajeReverso: "La belleza infinita reside en los anillos de cada promesa."
    },
    {
      nombre: "Urano",
      textura: "https://raw.githubusercontent.com/mrdoob/three.js/r128/examples/textures/planets/moon_1024.jpg",
      radio: 0.8,
      distancia: 26,
      velocidad: 0.07,
      colorFallback: 0x4dd0e1,
      colorTema: "#4dd0e1",
      video: "./assets/Ed-Sheeran-Perfect.mp4",
      info: "Ed Sheeran - Perfect.",
      mensajeReverso: "Girando a tu propio compás, original y auténtico."
    },
    {
      nombre: "Neptuno",
      textura: "https://raw.githubusercontent.com/mrdoob/three.js/r128/examples/textures/planets/moon_1024.jpg",
      radio: 0.75,
      distancia: 31,
      velocidad: 0.05,
      colorFallback: 0x3d5afe,
      colorTema: "#4464f2",
      info: "New West - Those Eyes.",
      video: "./assets/New-West-Those-Eyes/mp4",
      mensajeReverso: "Misterioso, calmo y profundo como la inmensidad del océano cósmico."
    }
  ],
  palabrasBonitas: [
  "Eres mi paz",
  "Eres mi hogar",
  "Eres mi alegría",
  "Eres mi felicidad",
  "Eres mi mundo",
  "Eres mi inspiración",
  "Eres mi sueño",
  "Eres mi razón",
  "Eres mi persona favorita",
  "Eres mi lugar favorito",
  "Eres muy especial",
  "Eres única",
  "Eres increíble",
  "Eres maravillosa",
  "Eres hermosa",
  "Eres perfecta para mí",
  "Me encantas",
  "Me haces feliz",
  "Me haces sonreír",
  "Me encanta tu sonrisa",
  "Me encanta tu mirada",
  "Me encanta tu forma de ser",
  "Me encanta estar contigo",
  "Me encanta tenerte",
  "Me encanta pensarte",
  "Me encanta escucharte",
  "Me encanta conocerte",
  "Me encanta coincidir contigo",
  "Me haces sentir especial",
  "Me haces sentir en casa",
  "Pienso mucho en ti",
  "Siempre pienso en ti",
  "Siempre estás en mi corazón",
  "Siempre estás en mi mente",
  "Siempre tú",
  "Solo tú",
  "Quiero estar contigo",
  "Quiero verte sonreír",
  "Quiero cuidarte",
  "Quiero acompañarte",
  "Quiero hacerte feliz",
  "Quiero compartir contigo",
  "Quiero seguir contigo",
  "Te quiero mucho",
  "Te quiero cada día más",
  "Te adoro",
  "Te extraño",
  "Te pienso",
  "Te admiro",
  "Te elijo",
  "Te cuido",
  "Te acompaño",
  "Te llevo conmigo",
  "Te llevo en mi corazón",
  "Te llevo en mis pensamientos",
  "Gracias por existir",
  "Gracias por llegar",
  "Gracias por estar",
  "Gracias por ser tú",
  "Gracias por hacerme feliz",
  "Qué bonito tenerte",
  "Qué bonito conocerte",
  "Qué bonito coincidir",
  "Qué bonito encontrarte",
  "Qué bonito quererte",
  "Qué bonito compartir contigo",
  "Contigo todo es bonito",
  "Contigo todo tiene sentido",
  "Contigo estoy feliz",
  "Contigo me siento bien",
  "Contigo soy feliz",
  "Contigo quiero estar",
  "Contigo me siento en casa",
  "Contigo aprendí a sonreír",
  "Tu sonrisa me encanta",
  "Tu mirada me enamora",
  "Tu forma de ser me encanta",
  "Tu presencia me alegra",
  "Tu voz me encanta",
  "Tu cariño me hace feliz",
  "Tu amor es especial",
  "Tu sonrisa ilumina todo",
  "Eres mi casualidad favorita",
  "Eres mi coincidencia favorita",
  "Eres mi pensamiento favorito",
  "Eres mi sonrisa favorita",
  "Eres mi bonito destino",
  "Eres una parte de mí",
  "Eres parte de mis días",
  "Eres parte de mis sueños",
  "Eres lo bonito de mis días",
  "Eres esa persona especial",
  "Eres alguien increíble",
  "Eres un regalo de la vida",
  "Me alegra haberte encontrado",
  "Me alegra tenerte en mi vida",
  "Me alegra coincidir contigo",
  "Me haces querer quedarme",
  "Siempre elegiría conocerte",
  "TE AMO"
  ],

  canciones: [
    {
      titulo: "Love Story",
      artista: "Indila",
      ruta: "./assets/Indila - Love Story.mp3"
    },
    {
      titulo: "Chainsaw Man",
      artista: "Kensuke Ushio",
      ruta: "./assets/Chainsaw Man Reze Arc OST - in the pool.mp3"
    },
    {
      titulo: "Luna",
      artista: "Zoe",
      ruta: "./assets/Zoe-LunaPiano.mp3"
    },
    {
      titulo: "Desde mi Cielo",
      artista: "Mago de Oz",
      ruta: "./assets/DesdemiCielo-MagodeOz.mp3"
    },
    {
      titulo: "Ofelia",
      artista: "Juan Arenosa",
      ruta: "./assets/JuanArenosa-Ofelia.mp3"
    }
    
  ]
  
};