export const CONFIG = {
  cantidadEstrellas: 160, // Cantidad de rosas flotantes
  texturaRosa: "./assets/rosa.png", // Imagen personalizada local
  sol: {
    nombre: "El Sol",
    info: "Lasso - No Pares de Bailar",
    radio: 2,
    textura: "./assets/sol.jpg",
    video: "./assets/lasso-no-pares-de-bailar.mp4",
    colorFallback: 0xffaa00,
    colorTema: "#ffaa00",
    mensajeReverso: "El sol se enamoró de la luna, y la luna del sol aunque sabían que no podían estar juntos, pero a veces se juntan y les importa una carajo si el mundo se oscurece!!."
    //Buenos días, buenas tardes o buenas noches, no sé a qué hora veas esto, hermosa. Hice esto especialmente para ti. Aunque el futuro sea incierto y no sepamos cuánto dure lo nuestro, quiero disfrutar hasta el último segundo a tu lado. Eres tan especial que te distinguiría a kilómetros. Pase lo que pase, quiero que esto quede como un bonito recuerdo de lo mucho que te quiero y te adoro.
  },
  planetas: [
    {
      nombre: "Mercurio",
       textura: "./assets/mercurio.jpg",
      radio: 0.3,
      distancia: 4,
      velocidad: 0.8,
      colorFallback: 0x9e9e9e,
      colorTema: "#a0a0a0",
      info: "Alex Ubago & Amaia Montero - Sin Miedo A Nada.",
      video: "./assets/alex-ubago-sin-miedo-a-nada.mp4",
      mensajeReverso: "El universo necesitó miles de millones de años para llegar hasta este instante. Yo solo necesitaba conocerte para querer detener el tiempo."
    },
    {
      nombre: "Venus",
      textura: "./assets/venus.jpg",
      radio: 0.5,
      distancia: 6,
      velocidad: 0.6,
      colorFallback: 0xe3bb76,
      colorTema: "#e8b86d",
      info: "Sin Bandera - Te Vi Venir",
      video: "./assets/Sin-Bandera-Te-Vi-Venir.mp4",
      mensajeReverso: "Te quiero ver y no puedo. Te quiero tener y no te tengo. Lo único que puedo hacer es quererte en silencio. Y no importa a qué hora mires esto, solo quiero decirte que hoy estoy pensando en ti como siempre."
    },
    {
      nombre: "Tierra",
      textura: "./assets/tierra.jpg",
      radio: 0.55,
      distancia: 8.5,
      velocidad: 0.4,
      colorFallback: 0x2b82c9,
      colorTema: "#2e93d8",
      info: "Andrés Cepeda - Un Ratito",
      video: "./assets/Andrés-Cepeda-Un-Ratito.mp4",
      mensajeReverso: "Entre miles de rosas, tú no serías la más linda, sino la más hermosa, porque entre todas ellas ninguna tendría tu dulce aroma."
    },
    {
      nombre: "Marte",
      textura: "./assets/marte.jpg",
      radio: 0.4,
      distancia: 11,
      velocidad: 0.3,
      colorFallback: 0xc1440e,
      colorTema: "#e05324",
      info: "Chayanne - Dejaría Todo",
      video: "./assets/Chayanne-Dejaría-Todo.mp4",
      mensajeReverso: "Por si nadie te lo ha dicho, a mí sí me importan tus problemas, a mí sí me importa tu salud, a mí sí me importan tus mensajes, a mí sí me importa cómo fue tu día, a mí sí me importa verte, a mí sí me importa escuchar tu opinión. En fin, a mí sí me importas, y muchísimo."
    },
    {
      nombre: "Júpiter",
      textura: "./assets/jupiter.jpg",
      radio: 1.5,
      distancia: 16,
      velocidad: 0.15,
      colorFallback: 0xd39c7e,
      colorTema: "#d89668",
      info: "Melendi - Destino o Casualidad ft. Ha*Ash",
      video: "./assets/Melendi-Destino-o-Casualidad.mp4",
      mensajeReverso: "Me dijieron que para enamorarte tenia que hacerte sonreír, pero cuando te veo sonreír el que se enamora soy yo."
    },
    {
      nombre: "Saturno",
      textura: "./assets/saturno.jpg",
      radio: 1.2,
      distancia: 21,
      velocidad: 0.1,
      colorFallback: 0xc5ab6e,
      colorTema: "#e2c575",
      video: "./assets/pablo-alborán-por-fin.mp4",
      tieneAnillo: true,
      info: "Pablo Alborán - Por fin.",
      mensajeReverso: "Incluso si nuestros gustos no coinciden, me gustaria ver tus series favoritas, probar la comida que te encanta, ir a esos lugares que te hacen feliz, escuchar tu artista favorito y descubrir todo lo que te gusta, solo para entenderte un poquito más."
    },
    {
      nombre: "Urano",
       textura: "./assets/urano.jpg",
      radio: 0.8,
      distancia: 26,
      velocidad: 0.07,
      colorFallback: 0x4dd0e1,
      colorTema: "#4dd0e1",
      video: "./assets/Ed-Sheeran-Perfect.mp4",
      info: "Ed Sheeran - Perfect.",
      mensajeReverso: "Perdón por insistir tanto, pero me arrepentiría el resto de mi vida si no hago hasta lo imposible para que te quedes."
    },
    {
      nombre: "Neptuno",
      textura: "./assets/neptuno.jpg",
      radio: 0.75,
      distancia: 31,
      velocidad: 0.05,
      colorFallback: 0x3d5afe,
      colorTema: "#4464f2",
      info: "New West - Those Eyes.",
      video: "./assets/New-West-Those-Eyes.mp4",
      mensajeReverso: "No siempre tengo cosas interesantes que contarte pero siempre tengo ganas de hablar contigo."
    }
  ],
  palabrasBonitas: [
  "Eres mi paz",
  "Eres mi hogar",
  "Eres mi alegría",
  "Eres mi felicidad",
  "Eres mi mundo",
  "Eres mi inspiración",
  "Eres mi sueño",
  "Eres mi razón",
  "Eres mi persona favorita",
  "Eres mi lugar favorito",
  "Eres muy especial",
  "Eres única",
  "Eres increíble",
  "Eres maravillosa",
  "Eres hermosa",
  "Eres perfecta para mí",
  "Me encantas",
  "Me haces feliz",
  "Me haces sonreír",
  "Me encanta tu sonrisa",
  "Me encanta tu mirada",
  "Me encanta tu forma de ser",
  "Me encanta estar contigo",
  "Me encanta tenerte",
  "Me encanta pensarte",
  "Me encanta escucharte",
  "Me encanta conocerte",
  "Me encanta coincidir contigo",
  "Me haces sentir especial",
  "Me haces sentir en casa",
  "Pienso mucho en ti",
  "Siempre pienso en ti",
  "Siempre estás en mi corazón",
  "Siempre estás en mi mente",
  "Siempre tú",
  "Solo tú",
  "Quiero estar contigo",
  "Quiero verte sonreír",
  "Quiero cuidarte",
  "Quiero acompañarte",
  "Quiero hacerte feliz",
  "Quiero compartir contigo",
  "Quiero seguir contigo",
  "Te quiero mucho",
  "Te quiero cada día más",
  "Te adoro",
  "Te extraño",
  "Te pienso",
  "Te admiro",
  "Te elijo",
  "Te cuido",
  "Te acompaño",
  "Te llevo conmigo",
  "Te llevo en mi corazón",
  "Te llevo en mis pensamientos",
  "Gracias por existir",
  "Gracias por llegar",
  "Gracias por estar",
  "Gracias por ser tú",
  "Gracias por hacerme feliz",
  "Qué bonito tenerte",
  "Qué bonito conocerte",
  "Qué bonito coincidir",
  "Qué bonito encontrarte",
  "Qué bonito quererte",
  "Qué bonito compartir contigo",
  "Contigo todo es bonito",
  "Contigo todo tiene sentido",
  "Contigo estoy feliz",
  "Contigo me siento bien",
  "Contigo soy feliz",
  "Contigo quiero estar",
  "Contigo me siento en casa",
  "Contigo aprendí a sonreír",
  "Tu sonrisa me encanta",
  "Tu mirada me enamora",
  "Tu forma de ser me encanta",
  "Tu presencia me alegra",
  "Tu voz me encanta",
  "Tu cariño me hace feliz",
  "Tu amor es especial",
  "Tu sonrisa ilumina todo",
  "Eres mi casualidad favorita",
  "Eres mi coincidencia favorita",
  "Eres mi pensamiento favorito",
  "Eres mi sonrisa favorita",
  "Eres mi bonito destino",
  "Eres una parte de mí",
  "Eres parte de mis días",
  "Eres parte de mis sueños",
  "Eres lo bonito de mis días",
  "Eres esa persona especial",
  "Eres alguien increíble",
  "Eres un regalo de la vida",
  "Me alegra haberte encontrado",
  "Me alegra tenerte en mi vida",
  "Me alegra coincidir contigo",
  "Me haces querer quedarme",
  "Siempre elegiría conocerte",
  "TE AMO"
  ],

  canciones: [
    {
      titulo: "Love Story",
      artista: "Indila",
      ruta: "./assets/Indila - Love Story.mp3"
    },
    {
      titulo: "Chainsaw Man",
      artista: "Kensuke Ushio",
      ruta: "./assets/Chainsaw Man Reze Arc OST - in the pool.mp3"
    },
    {
      titulo: "Luna",
      artista: "Zoe",
      ruta: "./assets/Zoe-LunaPiano.mp3"
    },
    {
      titulo: "Desde mi Cielo",
      artista: "Mago de Oz",
      ruta: "./assets/DesdemiCielo-MagodeOz.mp3"
    },
    {
      titulo: "Ofelia",
      artista: "Juan Arenosa",
      ruta: "./assets/JuanArenosa-Ofelia.mp3"
    }
    
  ]
  
};